# Generated by Django 3.2.5 on 2022-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('srno', models.ImageField(upload_to='')),
                ('ssec', models.CharField(max_length=4)),
                ('scourse', models.CharField(max_length=10)),
            ],
        ),
    ]
