# Generated by Django 3.2.5 on 2022-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='srno',
            field=models.ImageField(upload_to=''),
        ),
    ]
